---
env:
  AWS_REGION: "ap-southeast-2"
steps:
  - label: ":female-scientist::skin-tone-2: Test run..."
    command:
      - ".buildkite/cicd_bootstrap.sh"
    timeout_in_minutes: 20
    agents:
      queue: default
  - label: ":female-scientist::skin-tone-2: Source tfenv..."
    command:
      - "source ~/.bash_profile"
    timeout_in_minutes: 20
    agents:
      queue: default
  - label: ":female-scientist::skin-tone-2: Run terraform plan..."
    command:
      - "terraform plan -out=dev.tfplan"
    timeout_in_minutes: 20
    agents:
      queue: default