---
env:
  AWS_REGION: "ap-southeast-2"
steps:
  - label: ":female-scientist::skin-tone-2: Test run..."
    command:
      - ".buildkite/cicd_bootstrap.sh"
    timeout_in_minutes: 20
  - label: ":female-scientist::skin-tone-2: Terraform init..."
    command:
      - ".buildkite/scripts/terraform-init.sh"
    timeout_in_minutes: 20
  - label: ":female-scientist::skin-tone-2: Run terraform plan..."
    command:
      - ".buildkite/scripts/terraform-plan.sh"
    timeout_in_minutes: 20